# Generated by Django 4.2.1 on 2023-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_merchant_category_merchant_country_merchant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.IntegerField(),
        ),
    ]
