# Generated by Django 4.2.1 on 2023-10-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_merchant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='country',
            new_name='count',
        ),
    ]
