# Generated by Django 4.2.6 on 2023-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_count_merchant_country_alter_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='type',
            field=models.CharField(blank=True, choices=[('pub', 'Public'), ('priv', 'Private'), ('mix', 'Mixte')], max_length=20, null=True),
        ),
    ]
